### ISSUE TITLE
Deeputil

### ISSUE THREAD

**Issue by vivek6190** [deep-compute/deeputil#14]
@supriyopaul 

- Found one issue while running a small code for getting datetime from the package `deeputil`

Step followed:
- `pip install deeputil`

####  Script:
```python
from deeputil import *

print get_datetime(1432188772)
```

Error:
```python
Traceback (most recent call last):
  File "deeputil_check.py", line 1, in <module>
    from deeputil import *
  File "/home/deepcompute/virtualenv/deeputil/local/lib/python2.7/site-packages/deeputil/__init__.py", line 8, in <module>
    from . import misc
  File "/home/deepcompute/virtualenv/deeputil/local/lib/python2.7/site-packages/deeputil/misc.py", line 91, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
```

**Comment by vivek6190** [comment]
@supriyopaul

**Comment by supriyopaul** [comment]
@vivek6190  current version is python3 compatible. We're trying to make it both 2 and 3 compatible. For now you can install an older version that is python 2.7 compatible **pip install deeputil==0.1.2**
